apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: math-grader-cms
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containers:
        - volumeMounts:
            - mountPath: /app
              name: envfile
          image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: envfile
          secret:
            items:
              - key: latest
                path: .env
            secretName: MATH_GRADER_CMS_ENV_DEVELOP
