name: Build and Push

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      image: ${{ steps.tag.outputs.image }}
    steps:
      - uses: actions/checkout@v3

      - name: Get tag value
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "Working tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "image=ghcr.io/math-p-earth/math-grader-cms:$TAG" >> $GITHUB_OUTPUT

  build-push:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ needs.prepare.outputs.tag }}

    outputs:
      image: steps.tag.outputs.image != ''

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push 
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ needs.prepare.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
