name: Deploy to Cloud Run

on:
  push:
    branch:
      - master

env:
  REGION: asia-southeast1

permissions:
  contents: read
  # required by google-github-actions/auth@v0
  id-token: write

jobs:
  prepare:
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      image: ${{ steps.tag.outputs.image }}
    steps:
      - name: Get tag value
        id: tag
        run: |
          TAG=$(git describe --exact-match --match 'v*' HEAD)

          if [[ $? -eq 0 ]]; then
            echo "tag=$TAG" >> $GITHUB_OUTPUT
            echo "image=$REGION-docker.pkg.dev/math-p-earth/math-p-earth/math-grader-cms:$TAG" >> $GITHUB_OUTPUT
          fi

  build-push:
    needs: prepare
    if: ${{ needs.prepare.outputs.tag }}

    outputs:
      image: steps.tag.outputs.image != ''

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/198474744222/locations/global/workloadIdentityPools/pool/providers/github
          service_account: github-actions@math-p-earth.iam.gserviceaccount.com
          token_format: access_token

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ needs.prepare.outputs.image }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    needs:
      - prepare
      - build-push

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/198474744222/locations/global/workloadIdentityPools/pool/providers/github
          service_account: github-actions@math-p-earth.iam.gserviceaccount.com

      - name: Set metadata file
        run: |
          sed -i 's/\${IMAGE}/${{ needs.prepare.outputs.image }}/g' .github/workflows/metadatas/math-grader-cms.yml

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          metadata: .github/workflows/metadatas/math-grader-cms.yml
